title: Sean Plummer
author: Sean Plummer
email: snplmmr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to use GithubPages
# social links
twitter_username: your-twitter-handle
github_username:  snplmmr

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
