title: Sean Plummer
author: Sean Plummer
email: snplmmr [at] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PhD student in Statistics at Texas A&M university.
# social links
# twitter_username: your-twitter-handle
github_username:  snplmmr

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
